name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Local IPA
        run: |
          # Gera a pasta nativa do iOS primeiro
          npx expo prebuild --platform ios
          
          # Descobre onde o Node está e injeta direto na configuração interna que o Xcode lê
          NODE_PATH=$(which node)
          echo "export NODE_BINARY=$NODE_PATH" > ios/.xcode.env
          echo "Conteúdo injetado no .xcode.env:"
          cat ios/.xcode.env
          
          cd ios
          WORKSPACE_NAME=$(ls -d *.xcworkspace | head -n 1)
          SCHEME_NAME=$(basename "$WORKSPACE_NAME" .xcworkspace)
          
          echo "Compilando o esquema: $SCHEME_NAME usando o workspace: $WORKSPACE_NAME"
          
          xcodebuild -workspace "$WORKSPACE_NAME" -scheme "$SCHEME_NAME" -configuration Release -sdk iphoneos -derivedDataPath build -allowProvisioningUpdates=NO CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO clean build
          
          cd ..
          mkdir -p Payload
          cp -r ios/build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r meu-gerenciador-real.ipa Payload
          rm -rf Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: meu-gerenciador-ipa
          path: meu-gerenciador-real.ipa
