name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 18

      - name: Install Dependencies
        run: npm install

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Local IPA
        run: |
          npx expo prebuild --platform ios
          cd ios
          xcodebuild -workspace *.xcworkspace -scheme * -configuration Release -sdk iphoneos -allowProvisioningUpdates=NO CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO clean build
          mkdir -p ../Payload
          mv build/Release-iphoneos/*.app ../Payload/
          cd ..
          zip -r meu-gerenciador-real.ipa Payload
